#########################
## Sass Lint File for Britecharts
#########################
## Example: https://github.com/sasstools/sass-lint/blob/master/docs/sass-lint.yml
## Convert from scss-lint: http://sasstools.github.io/make-sass-lint-config/
#########################

files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 0
  class-name-format: 0
  clean-import-paths: 0
  empty-line-between-blocks: 0
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  function-name-format: 0
  hex-length: 0
  hex-notation: 0
  id-name-format: 0
  indentation:
    - 1
    - size: 4
  leading-zero: 0
  mixin-name-format: 0
  mixins-before-declarations: 1
  nesting-depth: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-duplicate-properties: 0
  no-important: 0
  no-mergeable-selectors: 0
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-trailing-zero: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  placeholder-in-extend: 0
  placeholder-name-format: 0
  property-sort-order: 0
  quotes: 0
  shorthand-values: 0
  single-line-per-selector: 0
  space-after-colon: 1
  space-after-comma: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens: 1
  trailing-semicolon: 1
  url-quotes: 0
  variable-name-format: 0
  zero-unit: 0
