---
exclude:
  - 'sass/bourbon/**'
  - 'sass/animate/_animate.scss'
linters:
  DeclarationOrder:
    enabled: true
  Indentation:
    enabled: true
    width: 4
  SpaceAfterPropertyColon:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceBetweenParens:
    enabled: true
  TrailingSemicolon:
    enabled: true
  FinalNewline:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  BorderZero:
    enabled: false
  CapitalizationInSelector:
    enabled: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  Comment:
    enabled: false
  Compass::*:
    enabled: false
  DuplicateProperty:
    enabled: false
  ElsePlacement:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  HexLength:
    enabled: false
  HexNotation:
    enabled: false
  IdWithExtraneousSelector:
    enabled: false
  ImportantRule:
    enabled: false
  ImportPath:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: false
  NameFormat:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  PropertySpelling:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  Shorthand:
    enabled: false
  SelectorFormat:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  StringQuotes:
    enabled: false
  UnnecessaryMantissa:
    enabled: false
  UrlFormat:
    enabled: false
  UrlQuotes:
    enabled: false
  ZeroUnit:
    enabled: false
  VendorPrefixes:
    enabled: false
  VendorPrefix:
    enabled: false
